services:
  ui:
    container_name: ui
    build:
      context: ..
      dockerfile: images/js.Dockerfile
    volumes:
      - .:/app
    ports:
      - 8001:5173

  api:
    container_name: api
    build:
      context: ..
      dockerfile: images/python.Dockerfile
    volumes:
      - .:/app
    ports:
      - 8002:8000
