build service:
	devcontainer build --workspace-folder . --config .devcontainer/{{service}}/devcontainer.json

up service:
	devcontainer up \
		--mount "type=bind,source=$HOME/.config/nvim,target=/home/${USER}/.config/nvim" \
		--mount "type=bind,source=$HOME/.gitconfig,target=/home/${USER}/.gitconfig" \
		--mount "type=bind,source=$HOME/.local/share/atuin,target=/home/${USER}/.local/share/atuin" \
		--mount "type=bind,source=$HOME/.local/share/nvim,target=/home/${USER}/.local/share/nvim" \
		--mount type=bind,source=$SSH_AUTH_SOCK,target=/ssh-agent \
		--workspace-folder . --remove-existing-container true \
		--config .devcontainer/{{service}}/devcontainer.json

enter service:
	docker exec -it -u {{ if service == "ui" { "node" } else { shell('whoami') } }} {{service}} bash

start:
	just up ui
	just up api
